# Generated by Django 4.2.20 on 2025-03-30 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chushou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ts_chushou',
            },
        ),
        migrations.CreateModel(
            name='Diqu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mingcheng', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fenlei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mingcheng', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Goumai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ts_goumai',
            },
        ),
        migrations.CreateModel(
            name='Guanli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ts_guanli',
            },
        ),
        migrations.CreateModel(
            name='Jingqu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('dizhi', models.CharField(blank=True, max_length=255, null=True)),
                ('dengji', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('jianjie', models.TextField()),
                ('zhuangtai', models.CharField(blank=True, default='待上架', max_length=255, null=True)),
                ('is_kaifang', models.CharField(blank=True, default='开放中', max_length=255, null=True)),
                ('is_shenhe', models.CharField(blank=True, default='待审核', max_length=255, null=True)),
                ('collect_num', models.CharField(blank=True, default='30', max_length=255, null=True)),
                ('diqu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.diqu')),
                ('fenlei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.fenlei')),
                ('maijia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.chushou')),
            ],
        ),
        migrations.CreateModel(
            name='Lb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='轮播')),
            ],
            options={
                'db_table': 'ts_lb',
            },
        ),
        migrations.CreateModel(
            name='Sc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_date', models.DateField(blank=True, null=True)),
                ('jingqu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.jingqu')),
                ('shui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.goumai')),
            ],
            options={
                'db_table': 'ts_sc',
            },
        ),
        migrations.CreateModel(
            name='Pl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_date', models.DateField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_shenhe', models.CharField(blank=True, default='待审核', max_length=255, null=True)),
                ('jingqu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.jingqu')),
                ('shui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.goumai')),
            ],
            options={
                'db_table': 'ts_pl',
            },
        ),
        migrations.CreateModel(
            name='Dingdan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmsj', models.DateField(blank=True, null=True)),
                ('maijia', models.CharField(blank=True, default='cs1', max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField()),
                ('zfzt', models.CharField(blank=True, default='待支付', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('addr', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('shui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.goumai')),
            ],
        ),
        migrations.CreateModel(
            name='Addr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('shouji', models.CharField(blank=True, max_length=255, null=True)),
                ('addr', models.CharField(blank=True, max_length=255, null=True)),
                ('shui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.goumai')),
            ],
        ),
    ]
