# Generated by Django 4.2.20 on 2025-05-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chushou',
            name='img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chushou',
            name='jianjie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goumai',
            name='img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goumai',
            name='jianjie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='diqu',
            table='ts_diqu',
        ),
        migrations.AlterModelTable(
            name='fenlei',
            table='ts_fenlei',
        ),
        migrations.AlterModelTable(
            name='jingqu',
            table='ts_jingqu',
        ),
    ]
