# Generated by Django 4.2.20 on 2025-05-25 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_chushou_img_url_chushou_jianjie_goumai_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dingdan',
            name='maijia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hello.chushou'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='addr',
            table='ts_addr',
        ),
        migrations.AlterModelTable(
            name='dingdan',
            table='ts_dingdan',
        ),
    ]
