# Generated by Django 4.2.20 on 2025-05-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_dingdan_maijia_alter_addr_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pl',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
