# Generated by Django 4.2.20 on 2025-05-26 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='lb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lb',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lb',
            name='img_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
