# Generated by Django 4.2.20 on 2025-05-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_lb_created_at_lb_title_alter_lb_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('sender_role', models.CharField(max_length=10)),
                ('receiver_id', models.IntegerField()),
                ('receiver_role', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ts_message',
            },
        ),
    ]
